Fix build failure with standard C 2023.
As initially identified in [Debian bug #1097774], raxml fails to build
with gcc 15, now defaulting on standard C 2023.  The error is:

	rmq.h:13:13: error: ‘bool’ cannot be defined via ‘typedef’
	   13 | typedef int bool;
	      |             ^~~~
	rmq.h:13:13: note: ‘bool’ is a keyword with ‘-std=c23’ onwards
	rmq.h:13:1: warning: useless type name in empty declaration
	   13 | typedef int bool;
	      | ^~~~~~~

The type bool is already defined starting with standard C 2023, so it
is necessary to check for the standard level before defining the type.

[Debian bug #1097774]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1097774

Signed-Off-By: Étienne Mollier <emollier@debian.org>